### ISSUE TITLE
Is this compatible with .net core - cross platform?

### ISSUE THREAD

**Issue by richardjharding** [jmecosta/sonar-fsharp-plugin#17]
Question - will this plugin work on linux build agents? or is it dependent on windows?

**Comment by jmecosta** [comment]
Should work. You need mono installed

**Comment by richardjharding** [comment]
awesome thanks  - I'm using the vsts docker agents which I think have the mono dependencies - I'll give it a go and report back

**Comment by richardjharding** [comment]
see #18  - version 1.02 works fine
