### ISSUE TITLE
Getting failed to parse file exception

### ISSUE THREAD

**Issue by tomaxsas** [jmecosta/sonar-fsharp-plugin#19]
Trying to run analysis wit latest 1.0.2 version. Getting 
`Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile` exception for all files. Tried to run manually, same error occurs.  No debug mode on runner, so cannot look deeper into it.

**Comment by jmecosta** [comment]
does that fail the analysis? can you share some code that causes that?

**Comment by tomaxsas** [comment]
For those files yes, i get 0 on all metrics. For example 
```fsharp
namespace Test

module Program =

    [<EntryPoint>]
    let main argv =
        Configurator.config |> WebApiSuave.startServer
        0

```

Even on this file shows 0 lines of code. I assume for some reason the fsharp linter fails, maybe upgrade to latest version? I tried to upgrade, but project uses old style project files, and i dont have visual studio.

**Comment by tomaxsas** [comment]
I tried to update all nuget to latest version. So now i'm not getting Lint Nok error, but the output xml file is not correct. it show 0 on all metrics.

**Comment by tomaxsas** [comment]
Sorry. Must bee looked at the wrong file. After updating nuget to latest the analysis runs fine. Can you please do the update, and release new version?

**Comment by jmecosta** [comment]
You mean from master? When you say you updated all nuget packages which ones are you referring. Maybe can you make a pull request?

**Comment by tomaxsas** [comment]
Currently i cannot do a pull requests. but what i did is update every single nuget to it's latests stable version and it worked.  Now i see some metrics on sonarqube, however i'm stuck on importing coverage and unit tests results report.  i'm using minicover and xunit, files are generated fine, coverage is in opencover format, unit tests in trx (vstest i think) but i cannot see them in sonarqube for some reason.

**Comment by jmecosta** [comment]
I have a plugin for converting open cover format to generic format that sq
uses if you want.

**Comment by tomaxsas** [comment]
i think it's worth a try

**Comment by jmecosta** [comment]
https://github.com/jmecsoftware/OpenCover2SonarConverter/releases

`Usage: OpenCoverPathConverter [OPTIONS]
Converts build path in xml files into another path

Options:
    /D|/d:<directory to look for files>
    /P|/p:<Pattern of files to search>
    /E|/e:<End Path to Use for path replacement in Report>
    /S|/s:<Search string for path replace in report>
    /R|/r:<covert reports : search string>
    /O|/o:<out file>
    /X|/x:<output xml>
Define both /d and /p
`

you can do path replacement, for example if your coverage reports are created in buildagents they might haev changing checkout folders so you will need to apply this path conversion so that it matches where you run the analysis

**Comment by vsobalski** [comment]
@tomaxsas you mentioned that updating the Nugets packages update fixed your problem. Did you update the packages from your project? If so, would you be able to post a list of your packages with the version associated with it? I am seeing a similar error I think: my report gets generated, but the log report _INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile_ and sonarqube doesn't interpret my code

**Comment by tomaxsas** [comment]
I updated all nugets on this plugin, recompiled it and uploaded on sonarqube. but soon fsharp was left behind so dont know current status of this.

**Comment by milbrandt** [comment]
> Trying to run analysis wit latest 1.0.2 version. Getting
> Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile exception for all files. Tried to run manually, same error occurs.  No debug mode on runner, so cannot look deeper into it.

Parse exception is a known limitation of 1.0.6.164 if no Visual Studio 2015 with F# is installed on build server.

**Comment by milbrandt** [comment]
use Plugin v1.1 (net472) or even v1.2 (dotnet Core 2.2) as soon as available
