### ISSUE TITLE
Importing test results and coverage are not working.

### ISSUE THREAD

**Issue by tomaxsas** [jmecosta/sonar-fsharp-plugin#20]
Tried to import tests results, but it failed. I'm using opencover format and mstest format. 
Searched for those keywords in this repository, but haven't found them, i assume it's not implemented, but readme says differently.

**Comment by jmecosta** [comment]
@tomaxsas have you tried the https://github.com/jmecsoftware/OpenCover2SonarConverter. 

i will at some point remove the test inport, since those can be imported using core features

**Comment by tomaxsas** [comment]
Yes i did. And it gave me error
```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.FSharp.Collections.MapTreeModule.find[TValue,a](IComparer`1 comparer, TValue k, MapTree`2 m)
   at Program.main$cont@12(FSharpMap`2 arguments, Unit unitVar) in E:\Development\SonarQube\jmecsoftware\OpenCoverConverter\OpenCoverPathConverter\Program.fs:line 18
   at Program.main(String[] argv) in E:\Development\SonarQube\jmecsoftware\OpenCoverConverter\OpenCoverPathConverter\Program.fs:line 12
```

**Comment by jmecosta** [comment]
Ok maybe I need to check. I've done this for c# . I will look over the
weekend

**Comment by jmecosta** [comment]
ok, can you try this:

OpenCoverPathConverter.exe /d PathWhereXmlFilesAre /p *.xml /o convertedCov.xml /x

ive uploaded a new version

**Comment by jmecosta** [comment]
https://github.com/jmecsoftware/OpenCover2SonarConverter/releases/download/1.0.1/OpenCoverConverter.zip

**Comment by jmecosta** [comment]
a few more explanations about this converter. You can have multiple open cover reports and and use /d for the directory where they are. So the converter will covert and merge all of them into a single xml /o file.xml that you can then use https://docs.sonarqube.org/display/SONAR/Generic+Test+Data to import the data.

if you want to have a more accurate branch coverage measure, then you can instead remove the /x argument from above and change the /o to /o convert.json. 

You can then install this plugin https://github.com/jmecsoftware/sonarqube-testdata-plugin  to get more accurate coverage data
