### ISSUE TITLE
Code Coverage - VSTest

### ISSUE THREAD

**Issue by alpacamybags118** [jmecosta/sonar-fsharp-plugin#21]
I've installed the plugin in my Sonar environment, and I'm using Team Foundation Server 2018 to run a CI workflow that will run f# unit tests, then report the results to Sonar. I'm running the tests using VSTest.

Currently, TFS is able to pick up the trx and coverage files and show code coverage metrics in the build summary, but Sonar is not picking up the coverage file. I've tried using both the sonar.fs.vscoveragexml.reportsPaths and the sonar.cs.vscoveragexml.reportsPaths. When I look at the output of the Sonar scanner, there is no mention of the sonar.fs.vscoveragexml.reportsPaths when I specify it, and when I use sonar.cs.vscoveragexml.reportsPaths, it picks up the coverage file, but then says it is unable to parse it.

Let me know if there is anything I can provide to help uncover what is happening

**Comment by peterquicken** [comment]
Upvoting this issue

**Comment by jmecosta** [comment]
@peterquicken @alpacamybags118 sorry however we will drop the support for those in plugin. There are already many alternatives that u can use for coverage like https://docs.sonarqube.org/latest/analysis/generic-test/ or https://github.com/jmecsoftware/sonarqube-testdata-plugin. coverage was kind of proto on top of c# dotnet tests library and the way it was maintained was not good.
