### ISSUE TITLE
unsatisfied dependency for Sonarqube 7.3

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#22]
Installed fsharp plugin 1.0.2 from here, SonarQube 7.3, fxcop plugin 1.4.1.

Using TFS 2015.3.1 on premise (15.117.27414.0)
TFS Sonarqube tasks: `Prepare Anaylsis Configuration` 4.* and `Run Code Analysis 4.*`

Building C# solution run code analysis is failing (no F# code in this solution):

>ERROR: Error during SonarQube Scanner execution
ERROR: Error during SonarQube Scanner execution
>
> ERROR: org.sonar.plugins.fsharp.FSharpSensor has unsatisfied dependency 'class org.sonar.plugins.fsharp.FsSonarRunnerExtractor' for constructor 'public org.sonar.plugins.fsharp.FSharpSensor(org.sonar.api.config.Settings,org.sonar.plugins.fsharp.FsSonarRunnerExtractor,org.sonar.api.batch.fs.FileSystem,org.sonar.api.measures.FileLinesContextFactory,org.sonar.api.issue.NoSonarFilter)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@146d80f:204<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@18cd76:219<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@10fd5a0:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@11373d3:40<|
ERROR: org.sonar.plugins.fsharp.FSharpSensor has unsatisfied dependency 'class org.sonar.plugins.fsharp.FsSonarRunnerExtractor' for constructor 'public org.sonar.plugins.fsharp.FSharpSensor(org.sonar.api.config.Settings,org.sonar.plugins.fsharp.FsSonarRunnerExtractor,org.sonar.api.batch.fs.FileSystem,org.sonar.api.measures.FileLinesContextFactory,org.sonar.api.issue.NoSonarFilter)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@146d80f:204<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@18cd76:219<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@10fd5a0:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@11373d3:40<|
ERROR: 
>
>The SonarQube Scanner did not complete successfully
The SonarQube Scanner did not complete successfully
16:34:29.511  Creating a summary markdown file...
>
>16:34:29.511 Post-processing failed. Exit code: 1
16:34:29.511  Post-processing failed. Exit code: 1
>
>E:\_1\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.4.1\classic-sonar-scanner-msbuild\SonarScanner.MSBuild.exe failed with return code: 1

**Comment by jmecosta** [comment]
What version are u using. We have tons of project like this and they dont
fail

**Comment by milbrandt** [comment]
Sorry, mixed lines up. Current release of your plugin downloaded this week: sonarqube-fsharp-plugin-1.0.2.jar
Using SonarQube server 7.3.0 Community Editon (Win7 64bit, Java8)

TFS Task Run Code Analysis 4.4.1
SonarScanner for MSBuild 4.4.2
SonarQube Scanner 3.2.0.1227

Upgrade was starting from Sonar 6.2. First update to 6.7.5 LTS. On both Releases no issue with the F# plugin.
Next step was upgrading to current Sonarqube 7.3 Community Edition.
While the F# scanner was in `extensions/plugins` reported exception happend. After deleting the Plugin the build on TFS was successful.

I observed on the [SDK for SonarQube Roslyn Analyzer Plugins](https://github.com/SonarSource/sonarqube-roslyn-sdk) that they differ with SDK 1.0 up to Sonar 6.7 and SDK 2.0 starting from Sonar 6.7. Seems like upgrade to 7.3 leads to some additional Tasks for me.

**Comment by jmecosta** [comment]
right, forgot to release this. Please get 1.0.3 and give it a try. thanks

**Comment by milbrandt** [comment]
I just gave it a first try and it seems to fulfill the reqauired dependencies. Closing therefore the issue. Thanks.
