### ISSUE TITLE
Update appveyour image to VS2019

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#34]
master branch is failing to build based on image change to VS 2019.
https://ci.appveyor.com/project/jorgecosta/sonar-fsharp-plugin-wxq94/builds/24946740

**Comment by jmecosta** [comment]
looks like java is also off

**Comment by milbrandt** [comment]
yes, seems so. You need to check if there is either a newer  Java 8.x or even Java 11. Sonarqube will go for Java 11 with release 8, so at the moment Java 8 would be the better choice. Maybe try to fix it in a branch first?

**Comment by jmecosta** [comment]
my guess, they having updated doc https://www.appveyor.com/docs/windows-images-software/#java even 2019 is not mention there. it might be that we have to dir the program files to find out what java is there. And also not sure if they even can use oracle jdk anymore because of the license change. if so we will need pull a  openjdk instead.

**Comment by milbrandt** [comment]
On Azure DevOps an hosted image with OpenJDK by Azul is available.
IMHO go for the Visual Studio 2017 Image with JDK 1.8 Update 162. That would be fine for SonarQube 7.x

**Comment by milbrandt** [comment]
Probably you should also increment the version, e.g. to 1.0.4, in all 3 pom files as the runtime changes (Java, VS201x).

**Comment by jmecosta** [comment]
So supose we move to azure pipelines

**Comment by jmecosta** [comment]
Lets put this compiling, we can then handke all thise

**Comment by milbrandt** [comment]
> So supose we move to azure pipelines

It's your project - thus you decide. If we want to go in direction SonarQube Marketplace (Issue #31) then it is required to integrate Sonarcloud Analysis in the build. But first master and the current PR #30 should be done before even thinking loud on such things.

**Comment by jmecosta** [comment]
fixed, later we can move to azure!
