### ISSUE TITLE
Add description and topics

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#37]
On the header of the start page https://github.com/jmecsoftware/sonar-fsharp-plugin
_No description, website, or topics provided_ and no topics are set.

Proposal for topics: fsharp, sonar-plugin, sonarqube, static-code-analysis (start typing, then topics are proposed)

Only the project administrator has the rights to set these.

**Comment by jmecosta** [comment]
👍
