### ISSUE TITLE
Broken Links in SonarQube-Administration-Marketplace

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#40]
In the Marketplace list of installed plugins the link to Homepage https://docs.sonarqube.org/display/PLUG/Plugin+Library/sonarqube-fsharp-plugin and Issue Tracker https://jira.sonarsource.com/secure/Dashboard.jspa don't match this plugin.

**Comment by jmecosta** [comment]
how do you update those? i dont think i have access to those

**Comment by milbrandt** [comment]
@jmecosta I don't know how, but it should be possible as other plugins have different options and links there. Probably these are the default from the template now and can be configured however it is done.

For me, it's not important but I wanted to write the issue down when I installed the latest build of master on our Sonarqube server.

**Comment by jmecosta** [comment]
Ah i think it can be configured in pom.xml. i think i understood the issue
now. I will check it later

**Comment by milbrandt** [comment]
fixed in v1.0.6.110
