### ISSUE TITLE
Update of sonar-dotnet-tests-library

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#44]
@jmecosta you have a fork https://github.com/jmecosta/sonar-dotnet-tests-library of this library. The file sonar-dotnet-tests-library-1.5-SNAPSHOT.jar in this repo seems to be newer. Is your fork still needed?

I found a reference to 7.9.1.7622 on the web. Did you do any special adjustments of the code? Can we just download any newer release and where to get it best?

**Comment by jmecosta** [comment]
currently we are trying to remove dependency to that library in some other plugins im working, and actually also remove coverage support from this plugin.

Currently the platform by default supports generic coverage reports https://docs.sonarqube.org/latest/analysis/generic-test/ also when working with it i found limitations so ive created a new plugin that is not language agnostic https://github.com/jmecsoftware/sonarqube-testdata-plugin u can read the motivation there if it makes. 

So i personally would be inclined to not support any coverage in the plugin and ask users to use either the generic importer or some other generic support.

**Comment by milbrandt** [comment]
So we should remove it also here? As you have done it already in other plugins I would appreciate it if you could deal with this as soon as we are on net472.

**Comment by jmecosta** [comment]
handled in #45
