### ISSUE TITLE
Replace deprecated Sonarqube API

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#46]
No deprecated APIs will be accepted for plugins, see https://docs.sonarqube.org/display/DEV/Versioning+and+API+Deprecation. Prerequisit for Issue #31 

- org.sonar.api.profiles.ProfileDefinition is deprecated and will be dropped in Sonarqube 8 (used in FSharpSonarWayProfile)

**Comment by jmecosta** [comment]
i can take care of that one, ive done afew already.

**Comment by jmecosta** [comment]
#47  closed
