### ISSUE TITLE
Analyze plugin in Sonarcloud

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#53]
An requirement of Sonarqube for deploying plugins to their Marketplace:

> It is analyzed on SonarCloud and the quality gate is green when doing a release. 

See [Deploying to the Marketplace, no. 7](https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace)

**Comment by jmecosta** [comment]
Supose it cant be done? Since we cant have there the f# plugin?

**Comment by milbrandt** [comment]
Asked in sonar community forum for advice, see https://community.sonarsource.com/t/link-to-f-plugin-goes-to-a-fork/9905/7 as other language analyzers probably had the same issue in the past already

**Comment by milbrandt** [comment]
At least the java part can be analyzed in Sonarcloud

**Comment by otrosien** [comment]
beware also of rule 3e: "The key of your plugin must be: not just the name of a language (e.g. cannot be java, rust, js/javascript, ...)"

**Comment by milbrandt** [comment]
The [answer from Sonarqube](https://community.sonarsource.com/t/how-to-analyze-new-language-on-sonarcoud-from-appveyor/10845) in their community forum was that it is fine if only Java part is analyzed. That should be possible with the Maven scanner.
Unforunately there is no direct support for Appveyor available (like eg for Azure DevOps) this the upload to SonarCloud will have to be sone with a Ssttings file as described in the Maven scanner instruction.

**Comment by milbrandt** [comment]
@jmecosta I would propose to do These steps only for net472 analyzer and when #62 is fixed. What's your Point of view? Further as it's your repository you should propably also be the owner of the Sonarcloud.io account.

**Comment by jmecosta** [comment]
i dont mind either way. feel free to put into the marketplace at your own pace :)

**Comment by milbrandt** [comment]
WIP: https://sonarcloud.io/dashboard?id=jmecsoftware.sonarqube.fsharp%3Asonar-communityfsharp-analyzer
