### ISSUE TITLE
The key of your plugin must be: not just the name of a language (e.g. cannot be java, rust, js/javascript, ...)

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#62]
beware also of rule 3e: "The key of your plugin must be: not just the name of a language (e.g. cannot be java, rust, js/javascript, ...)"

_Originally posted by @otrosien in https://github.com/jmecsoftware/sonar-fsharp-plugin/issues/53#issuecomment-502960729_

**Comment by milbrandt** [comment]
Thanks @otrosien I moved this to a separate issue as it has nothing do do with analyzing in sonarcloud. It is an important Point, even while there are other plugins on the market place which don't obey (eg Haskell). Contributors and supporters are always welcome ;)

@jmecosta Do have any preferences? Probably the key and the name should indicate the that this plugin is open source.

**Comment by jmecosta** [comment]
sonar-fsharp?

**Comment by otrosien** [comment]
I was thinking the same for my perl plugin (still waiting for confirmation that this is doable here: https://community.sonarsource.com/t/new-release-perl-plugin-0-4-0/5569/8?u=otrosien )

**Comment by otrosien** [comment]
dashes are not allowed btw.

**Comment by milbrandt** [comment]
Thanks Oliver, I'll watch your communication with Ann - but she mentioned in another thread to be out of office this week. The question regarding breaking all existing installations came also to my mind.

As your plugin is further down the road to marketplace we'll observe. For me `sonarfsharp` or `communityfsharp` would both be fine.

**Comment by milbrandt** [comment]
@jmecosta I would go for `communityfsharp` if it's ok for you as `sonarXXX` as in the above linked discussion there was a statement "although there’s nothing in the rules (yet!" - and I wouldn't like to make a breaking change of the key twice.
