### ISSUE TITLE
[1.1.0.200] Unable to read plugin manifest from jar

### ISSUE THREAD

**Issue by megaDeej** [jmecosta/sonar-fsharp-plugin#80]
**Describe the bug**
When trying to install the latest version of the plugin, we are receiving this error: Unable to read plugin manifest from jar : C:\sonarqube-enterprise\sonarqube-7.9.1\extensions\plugins\sonarqube-fsharp-plugin-1.1.0.200.jar

Do you happen to know what might be going on?

**To Reproduce**
1. Install plugin in the proper way and restart the SonarQube service
2. See error

**Comment by milbrandt** [comment]
Sorry, no I haven't seen this up to now.
As this was from the major PR #30 which changed and fixed a lot, could you please give the latest release [2.0.0.279](https://github.com/jmecsoftware/sonar-fsharp-plugin/releases) a try with SonarQube 7.9.1? I would be very interessted in the result as in the company we're still on SonarQube Developer 7.7 with JRE 8.

**Comment by milbrandt** [comment]
Please be aware, that the plugin jar and key was renamed with 2.0

**Comment by megaDeej** [comment]
Sure I'll try and get it installed ASAP.  Thanks!

**Comment by milbrandt** [comment]
Thanks, and maybe you get more information if you increase the log level.
The Jar was downloaded successfuly? On stackoverflow I found a report of your error message where the jar was broken (and an exception logged previously).

**Comment by milbrandt** [comment]
For testing purpose I created an Azure VM with Azul Zulu JDK 11 and installed SonarQube Community 7.9.1 with test database H2 there. When starting Sonarqube Server (with `StartSonar.bat`, not as a service) SonarQube started successfully and displayed the F# plugin for 1.1.0.200 as well as 2.0.0.279

**Comment by megaDeej** [comment]
I was able to get the latest version installed, currently testing now, but I did not see this error come up again.  Thanks for your help
