### ISSUE TITLE
Replace deprecated Sonarqube API (7.9 LTS)

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#83]
No deprecated APIs will be accepted for plugins, see https://docs.sonarqube.org/latest/extend/developing-plugin/#header-3. Prerequisit for Issue #31

Currently still in branch feature/updates

**Comment by milbrandt** [comment]
@jmecosta could you take care of this issue please? Last time you upgraded the API for this plugin and others from your company. 
SonarQube 8.2 now removed some APIs deprected in 6.x.

**Comment by jmecosta** [comment]
Yep, i can handle it

**Comment by jmecosta** [comment]
next month i will do this!

**Comment by jmecosta** [comment]
handled in #100
